name: Dispatch update
on:
  - push
  - workflow_dispatch
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Push to repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: stratum-mining/stratumprotocol.org
          event-type: update-submodule
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "src/specification", "branch": "main"}'
